### ISSUE TITLE
Error: zathura: SHA256 mismatch

### ISSUE THREAD

**Issue by tim0120** [zegervdv/homebrew-zathura#105]
Trying to install zathura with `brew install zathura`, and I keep getting the error in the title (i.e., "Error: zathura: SHA256 mismatch").

As suggested, I delete the suggested tar file associated with girara and run the command again, but I still get the same SHA256 error.
Any suggestions how to resolve this?
Thanks!

**Comment by tim0120** [comment]
I can also share more information if that is useful in resolving this!

**Comment by zegervdv** [comment]
Github [changed](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/) the tarball compression which modified all checksums.
They've reverted it for now, so it should work again.

**Comment by tim0120** [comment]
Problem seems to be that I am using a silicon Mac and trying install zathura. My apologies.

**Comment by zegervdv** [comment]
It should also work on an M1 (so probably M2 too). 
The SHA checksum is done over the source code tar archive we download before compiling zathura for your machine.

If you remove the downloaded archive one last time and try to install it, you should at least get past the checksum error.
If you see any other issues, let me know.

Normally it will print a location to a log file if something fails, you can attach (the error part of) that file to help figure out what the issue is.

**Comment by tim0120** [comment]
That does work now, thanks for the update on the Github changes. Was not aware of that.
