### ISSUE TITLE
zathura 0.3.9 is released

### ISSUE THREAD

**Issue by phye** [zegervdv/homebrew-zathura#22]
Can you update your repo to point to the latest source?

Thanks

**Comment by phye** [comment]
Just tried myself, found out that zathura authors are switching from Makefile to meson, possibly for all other dependent components like girara .etc. 

As 0.3.9 ships with HiDPI support, this is really a *tremendous* upgrade.

**Comment by zegervdv** [comment]
I managed to update girara and zathura to the latest versions (after some fooling around with the meson tool) but I can't get the plugins to work yet.

You may need to manually install meson from source because of mesonbuild/meson#3493:
~~~
brew install --HEAD meson
~~~

I need to figure out a way to cleanly install the plugins to the right directory without violating the sandboxing.

**Comment by zegervdv** [comment]
Found a workaround for the `zathura-pdf-poppler` plugin but it still needs some manual action afterwards. I will update the other plugins later this week.

**Comment by phye** [comment]
Sorry, I forgot to install the correct `meson`, the logs above were due to that I was using the meson installed via `brew install meson` manually back to weeks ago when I was building them from source. 

After removing meson and install the correct one (`brew install --HEAD meson`), I can build zathura now.

Thanks.
